/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicSessionsRouteImport } from './routes/api/public/sessions'
import { Route as ApiPublicSessionsSessionIdRouteImport } from './routes/api/public/sessions.$sessionId'
import { Route as ApiPublicIngestSessionIdFramesRouteImport } from './routes/api/public/ingest.$sessionId.frames'
import { Route as ApiPublicSessionsSessionIdBoundaryFrameRouteImport } from './routes/api/public/sessions.$sessionId.boundary-frame'
import { Route as ApiPublicSessionsSessionIdCalibrationRouteImport } from './routes/api/public/sessions.$sessionId.calibration'
import { Route as ApiPublicSessionsSessionIdViolationsRouteImport } from './routes/api/public/sessions.$sessionId.violations'
import { Route as ApiPublicSessionsSessionIdViolationsViolationIdRouteImport } from './routes/api/public/sessions.$sessionId.violations.$violationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSessionsRoute = ApiPublicSessionsRouteImport.update({
  id: '/api/public/sessions',
  path: '/api/public/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSessionsSessionIdRoute =
  ApiPublicSessionsSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => ApiPublicSessionsRoute,
  } as any)
const ApiPublicIngestSessionIdFramesRoute =
  ApiPublicIngestSessionIdFramesRouteImport.update({
    id: '/api/public/ingest/$sessionId/frames',
    path: '/api/public/ingest/$sessionId/frames',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSessionsSessionIdBoundaryFrameRoute =
  ApiPublicSessionsSessionIdBoundaryFrameRouteImport.update({
    id: '/boundary-frame',
    path: '/boundary-frame',
    getParentRoute: () => ApiPublicSessionsSessionIdRoute,
  } as any)
const ApiPublicSessionsSessionIdCalibrationRoute =
  ApiPublicSessionsSessionIdCalibrationRouteImport.update({
    id: '/calibration',
    path: '/calibration',
    getParentRoute: () => ApiPublicSessionsSessionIdRoute,
  } as any)
const ApiPublicSessionsSessionIdViolationsRoute =
  ApiPublicSessionsSessionIdViolationsRouteImport.update({
    id: '/violations',
    path: '/violations',
    getParentRoute: () => ApiPublicSessionsSessionIdRoute,
  } as any)
const ApiPublicSessionsSessionIdViolationsViolationIdRoute =
  ApiPublicSessionsSessionIdViolationsViolationIdRouteImport.update({
    id: '/$violationId',
    path: '/$violationId',
    getParentRoute: () => ApiPublicSessionsSessionIdViolationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/sessions': typeof ApiPublicSessionsRouteWithChildren
  '/api/public/sessions/$sessionId': typeof ApiPublicSessionsSessionIdRouteWithChildren
  '/api/public/ingest/$sessionId/frames': typeof ApiPublicIngestSessionIdFramesRoute
  '/api/public/sessions/$sessionId/boundary-frame': typeof ApiPublicSessionsSessionIdBoundaryFrameRoute
  '/api/public/sessions/$sessionId/calibration': typeof ApiPublicSessionsSessionIdCalibrationRoute
  '/api/public/sessions/$sessionId/violations': typeof ApiPublicSessionsSessionIdViolationsRouteWithChildren
  '/api/public/sessions/$sessionId/violations/$violationId': typeof ApiPublicSessionsSessionIdViolationsViolationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/sessions': typeof ApiPublicSessionsRouteWithChildren
  '/api/public/sessions/$sessionId': typeof ApiPublicSessionsSessionIdRouteWithChildren
  '/api/public/ingest/$sessionId/frames': typeof ApiPublicIngestSessionIdFramesRoute
  '/api/public/sessions/$sessionId/boundary-frame': typeof ApiPublicSessionsSessionIdBoundaryFrameRoute
  '/api/public/sessions/$sessionId/calibration': typeof ApiPublicSessionsSessionIdCalibrationRoute
  '/api/public/sessions/$sessionId/violations': typeof ApiPublicSessionsSessionIdViolationsRouteWithChildren
  '/api/public/sessions/$sessionId/violations/$violationId': typeof ApiPublicSessionsSessionIdViolationsViolationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/sessions': typeof ApiPublicSessionsRouteWithChildren
  '/api/public/sessions/$sessionId': typeof ApiPublicSessionsSessionIdRouteWithChildren
  '/api/public/ingest/$sessionId/frames': typeof ApiPublicIngestSessionIdFramesRoute
  '/api/public/sessions/$sessionId/boundary-frame': typeof ApiPublicSessionsSessionIdBoundaryFrameRoute
  '/api/public/sessions/$sessionId/calibration': typeof ApiPublicSessionsSessionIdCalibrationRoute
  '/api/public/sessions/$sessionId/violations': typeof ApiPublicSessionsSessionIdViolationsRouteWithChildren
  '/api/public/sessions/$sessionId/violations/$violationId': typeof ApiPublicSessionsSessionIdViolationsViolationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/sessions'
    | '/api/public/sessions/$sessionId'
    | '/api/public/ingest/$sessionId/frames'
    | '/api/public/sessions/$sessionId/boundary-frame'
    | '/api/public/sessions/$sessionId/calibration'
    | '/api/public/sessions/$sessionId/violations'
    | '/api/public/sessions/$sessionId/violations/$violationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/sessions'
    | '/api/public/sessions/$sessionId'
    | '/api/public/ingest/$sessionId/frames'
    | '/api/public/sessions/$sessionId/boundary-frame'
    | '/api/public/sessions/$sessionId/calibration'
    | '/api/public/sessions/$sessionId/violations'
    | '/api/public/sessions/$sessionId/violations/$violationId'
  id:
    | '__root__'
    | '/'
    | '/api/public/sessions'
    | '/api/public/sessions/$sessionId'
    | '/api/public/ingest/$sessionId/frames'
    | '/api/public/sessions/$sessionId/boundary-frame'
    | '/api/public/sessions/$sessionId/calibration'
    | '/api/public/sessions/$sessionId/violations'
    | '/api/public/sessions/$sessionId/violations/$violationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicSessionsRoute: typeof ApiPublicSessionsRouteWithChildren
  ApiPublicIngestSessionIdFramesRoute: typeof ApiPublicIngestSessionIdFramesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sessions': {
      id: '/api/public/sessions'
      path: '/api/public/sessions'
      fullPath: '/api/public/sessions'
      preLoaderRoute: typeof ApiPublicSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sessions/$sessionId': {
      id: '/api/public/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/api/public/sessions/$sessionId'
      preLoaderRoute: typeof ApiPublicSessionsSessionIdRouteImport
      parentRoute: typeof ApiPublicSessionsRoute
    }
    '/api/public/ingest/$sessionId/frames': {
      id: '/api/public/ingest/$sessionId/frames'
      path: '/api/public/ingest/$sessionId/frames'
      fullPath: '/api/public/ingest/$sessionId/frames'
      preLoaderRoute: typeof ApiPublicIngestSessionIdFramesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sessions/$sessionId/boundary-frame': {
      id: '/api/public/sessions/$sessionId/boundary-frame'
      path: '/boundary-frame'
      fullPath: '/api/public/sessions/$sessionId/boundary-frame'
      preLoaderRoute: typeof ApiPublicSessionsSessionIdBoundaryFrameRouteImport
      parentRoute: typeof ApiPublicSessionsSessionIdRoute
    }
    '/api/public/sessions/$sessionId/calibration': {
      id: '/api/public/sessions/$sessionId/calibration'
      path: '/calibration'
      fullPath: '/api/public/sessions/$sessionId/calibration'
      preLoaderRoute: typeof ApiPublicSessionsSessionIdCalibrationRouteImport
      parentRoute: typeof ApiPublicSessionsSessionIdRoute
    }
    '/api/public/sessions/$sessionId/violations': {
      id: '/api/public/sessions/$sessionId/violations'
      path: '/violations'
      fullPath: '/api/public/sessions/$sessionId/violations'
      preLoaderRoute: typeof ApiPublicSessionsSessionIdViolationsRouteImport
      parentRoute: typeof ApiPublicSessionsSessionIdRoute
    }
    '/api/public/sessions/$sessionId/violations/$violationId': {
      id: '/api/public/sessions/$sessionId/violations/$violationId'
      path: '/$violationId'
      fullPath: '/api/public/sessions/$sessionId/violations/$violationId'
      preLoaderRoute: typeof ApiPublicSessionsSessionIdViolationsViolationIdRouteImport
      parentRoute: typeof ApiPublicSessionsSessionIdViolationsRoute
    }
  }
}

interface ApiPublicSessionsSessionIdViolationsRouteChildren {
  ApiPublicSessionsSessionIdViolationsViolationIdRoute: typeof ApiPublicSessionsSessionIdViolationsViolationIdRoute
}

const ApiPublicSessionsSessionIdViolationsRouteChildren: ApiPublicSessionsSessionIdViolationsRouteChildren =
  {
    ApiPublicSessionsSessionIdViolationsViolationIdRoute:
      ApiPublicSessionsSessionIdViolationsViolationIdRoute,
  }

const ApiPublicSessionsSessionIdViolationsRouteWithChildren =
  ApiPublicSessionsSessionIdViolationsRoute._addFileChildren(
    ApiPublicSessionsSessionIdViolationsRouteChildren,
  )

interface ApiPublicSessionsSessionIdRouteChildren {
  ApiPublicSessionsSessionIdBoundaryFrameRoute: typeof ApiPublicSessionsSessionIdBoundaryFrameRoute
  ApiPublicSessionsSessionIdCalibrationRoute: typeof ApiPublicSessionsSessionIdCalibrationRoute
  ApiPublicSessionsSessionIdViolationsRoute: typeof ApiPublicSessionsSessionIdViolationsRouteWithChildren
}

const ApiPublicSessionsSessionIdRouteChildren: ApiPublicSessionsSessionIdRouteChildren =
  {
    ApiPublicSessionsSessionIdBoundaryFrameRoute:
      ApiPublicSessionsSessionIdBoundaryFrameRoute,
    ApiPublicSessionsSessionIdCalibrationRoute:
      ApiPublicSessionsSessionIdCalibrationRoute,
    ApiPublicSessionsSessionIdViolationsRoute:
      ApiPublicSessionsSessionIdViolationsRouteWithChildren,
  }

const ApiPublicSessionsSessionIdRouteWithChildren =
  ApiPublicSessionsSessionIdRoute._addFileChildren(
    ApiPublicSessionsSessionIdRouteChildren,
  )

interface ApiPublicSessionsRouteChildren {
  ApiPublicSessionsSessionIdRoute: typeof ApiPublicSessionsSessionIdRouteWithChildren
}

const ApiPublicSessionsRouteChildren: ApiPublicSessionsRouteChildren = {
  ApiPublicSessionsSessionIdRoute: ApiPublicSessionsSessionIdRouteWithChildren,
}

const ApiPublicSessionsRouteWithChildren =
  ApiPublicSessionsRoute._addFileChildren(ApiPublicSessionsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicSessionsRoute: ApiPublicSessionsRouteWithChildren,
  ApiPublicIngestSessionIdFramesRoute: ApiPublicIngestSessionIdFramesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
